client_id         = "your-service-principal-app-id"
client_secret     = "your-service-principal-secret"
subscription_id   = "your-azure-subscription-id"
tenant_id         = "your-azure-tenant-id"
resource_group    = "your-resource-group-name"
location          = "East US"
image_name        = "win2022-devops-agent"
image_version     = "1.0.0"